<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.qa.RDE.automation.RDEUI.core.generic.utilities.CucumberRunner" tests="1" time="267.886" ignored="0" failures="0" timestamp="18 Apr 2018 16:32:46 GMT" skipped="0" hostname="LH7U05CG5160RK3" errors="1">
  <testcase name="feature" time="267.886" classname="com.qa.RDE.automation.RDEUI.core.generic.utilities.CucumberRunner">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Failed in Testng helper">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Failed in Testng helper
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Failed in Testng helper
	at org.testng.Assert.fail(Assert.java:94)
	at com.qa.RDE.automation.RDEUI.core.generic.utilities.TestNGHelper.fail(TestNGHelper.java:63)
	at com.qa.RDE.automation.RDEUI.core.generic.utilities.SeleniumHelper.waitForAjaxElementToBePresent_poc(SeleniumHelper.java:3659)
	at com.qa.RDE.automation.RDEUI.core.generic.utilities.SeleniumHelper.findElement_poc(SeleniumHelper.java:3352)
	at com.qa.RDE.automation.RDEUI.automation.pages.RDE_GeneralInformationQuestionsPage.doYouContinueMEdicalCoverage_ListBox(RDE_GeneralInformationQuestionsPage.java:58)
	at com.qa.RDE.automation.RDEUI.automation.pages.RDE_GeneralInformationQuestionsPage.Enter_GeneralInfoQuestionsRegardingGroupSize(RDE_GeneralInformationQuestionsPage.java:290)
	at com.qa.RDE.automation.RDEUI.automation.steps.RDESteps.enter_General_Information_Questions_Regarding_GroupSize_with_below_Input_Data(RDESteps.java:139)
	at âœ½.When Enter General Information Questions Regarding GroupSize with below Input Data(src/test/resources/Feature/RDE.feature:38)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.qa.RDE.automation.RDEUI.core.generic.utilities.CucumberRunner -->
